# Generated by Django 3.0 on 2019-12-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20191226_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(upload_to='video_thumbnails/'),
        ),
    ]
