# Generated by Django 3.0 on 2019-12-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20191226_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(upload_to='videos/video_thumbnails/'),
        ),
    ]
