# Generated by Django 3.0.1 on 2019-12-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20191226_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(blank=True, upload_to='media/videos/video_thumbnails/'),
        ),
    ]
