# Generated by Django 3.0.1 on 2019-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20191227_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
