# Generated by Django 3.0.1 on 2019-12-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20191227_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='media/video/video_thumbnails'),
        ),
    ]
