# Generated by Django 3.0.1 on 2020-01-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200111_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_thumbnail',
            field=models.ImageField(blank=True, upload_to='video/video_thumbnails'),
        ),
    ]
