# Generated by Django 3.0.1 on 2020-01-11 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_auto_20200111_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecharacter',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='video',
            name='number',
        ),
        migrations.DeleteModel(
            name='Auther',
        ),
        migrations.DeleteModel(
            name='MovieCharacter',
        ),
        migrations.DeleteModel(
            name='VideoNumber',
        ),
    ]
