# Generated by Django 3.0.1 on 2020-01-18 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcasts',
            name='revised_date',
        ),
    ]
