# Generated by Django 3.0.1 on 2020-01-18 22:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('podcast', '0002_remove_podcasts_revised_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Podcasts',
            new_name='Podcast',
        ),
    ]
