# Generated by Django 3.0.1 on 2020-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_comment_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='promoted',
            field=models.IntegerField(choices=[(0, 'Nonpromo'), (1, 'Promo'), (2, 'Bigpromo'), (3, 'Hugepromo')], default=0),
        ),
    ]
