# Generated by Django 3.0.1 on 2020-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200126_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_real_name',
            field=models.TextField(blank=True),
        ),
    ]
